### PR TITLE
Title, Box, Content,Tag and Delete is working

### PR DESCRIPTION
**Pull request by kunjee17**
Hey, Title is finally working. Please have a look. 
> Have used List.fold instead of recursive function. If that is ok?

### CODE REVIEW

**Comment by kunjee17** [comment]
Delete is also working. 

PS: Should I be giving different PR or it is ok If add commits to single PR until you merged them as right now not many people are working?

**Comment by kunjee17** [comment]
Box is working. 
> There is minor issue in demo code. It is breaking 2 column layout. I couldn't fix it as it is generating proper code. Please have a look if you find it blocker.

**Comment by kunjee17** [comment]
Box documentation issued solved. And content is also done.

**Comment by MangelMaxime** [comment]
Thanks for all this contributions @kunjee17 
Yes I would actually prefer severals PR to allow an easier review :)

I didn't know of `List.fold` I will use it now :)
And I will refactor some part of the code just to have the same way of formatting the record everywhere :)

**Comment by kunjee17** [comment]
Hey, sorry I just completed tag before you commented. So from now on will give different PRs. And let me know wherever correction is required. And thanks for project.

**Pull request merged**
