### PR TITLE
Add Font Awesome support via convenience functions

### PR DESCRIPTION
**Pull request by MangelMaxime**
Here is my current proposition for adding support of FontAwesome icons. Related to #24 

The function `Icon.faIcon` almost follow the standard DSL only the second argument isn't a list.
Also, the user can still use:

- `Icon.isSmall`
- `Icon.customClass`
- `Icon.props [ OnClick .... ]`
- etc.

So we don't limit his possibilities.

Last, I added intellisense for all the icons supported by Font Awesome `4.7.0`. I made a really some JS script to generate the DU case, I only have 2 fixs to make to the DU due to F# "limitations".

Here is an screen of the updated version of Icons documentation. To avoid you to build it :)

image

@rmunn Can you give me your opinion ?

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
Having intellisense for the Font Awesome icons is great! :clap: :clap: I don't have to continuously check the web site anymore ;)

**Comment by rmunn** [comment]
This is exactly what I was requesting. Pulling all the Font Awesome icon names into a StringEnum DU was even more than I had asked for. I'd thought about asking for it, but thought it would be too much work, so I decided to ask for something more limited in scope. Writing a scraper script to extract the names was a brilliant idea.

Furthermore, this design looks extensible to other icon sets, whether they're font icon sets or SVG icon sets. You'd have to tweak the scraper script for the particulars of each icon set's website, but this way it will be easy to respond to user requests for icon sets like [Glyph](http://glyph.smarticons.co/) or other icons. The convenience function would generate different HTML (`img` or `svg-icon` for Glyph, for example), but the "shape" of the convenience function would stay the same (`Icon.GlyphIcon [ Icon.isSmall ] Glyph.AlarmClock`). So as use of Fable.Elmish.Bulma grows and you get user requests for other icon sets, you can add them on an as-needed basis. (I'm not suggesting that you add them all right now: add Font Awesome, the icon set with the most popularity right now, and get the kinks worked out on FA. Then you can add other icon sets if there's demand for them.)

The only thing I would add is another line of documentation showing how to use `Fa.Custom`. E.g.,

```fsharp
// If the "fa-thumbs-up" icon was missing, you could use Fa.Custom to get it:
Icon.FaIcon [ Icon.isLarge ] (Fa.Custom "fa-thumbs-up")
```

The usage example will be most useful for people who aren't quite certain of F# syntax and might leave out the parentheses (and then would not understand why that produces a compiler error).

**Comment by whitetigle** [comment]
This is a great move @MangelMaxime! Now we have a quite complete set of features for Elmish apps. We can definitely start marketing these tools 😉  

Congratulations! 🍾 🍾 

I have been using Elmish + Bulma every day for some weeks now and it's now quite clear that it as genuinely boosted my productivity while strengthening my code base. 👍 🥂

**Comment by MangelMaxime** [comment]
@rmunn Adding the `Fa.Custom` sample is a really good idea, I will add it.

@alfonsogarciacaro Yes having intellisense everywhere is one of the strengh of Elmish.Bulma even over the Bulma classes you can get intellisense and help thanks to `BulmaClasses.fs` and was the main reason of this project. No one like writing string and debugging them :)

@whitetigle Really happy to hear that this project help you in your work and boosted your productivity :) And yes, we are close to marketing these tools we are just missing a documentation about the Elmish.Bulma structure and how it install it. Then we are good to go even if we don't have all the components yet (Bulma, is evolving really quickly these days (2-3 release happened since I started this project.

**Comment by rmunn** [comment]
Very nice! But I made a mistake in my sample code. See #26.

**Pull request merged**
