### PR TITLE
Create and set icon for nuget :)

### PR DESCRIPTION
**Pull request by evilz**

### CODE REVIEW

**Comment by alfonsogarciacaro** [comment]
You can create icons for Nuget? I want this too! :wink:

**Comment by MangelMaxime** [comment]
Thanks you :)

**Comment by evilz** [comment]
Less pixelized but difform ;)

**Comment by MangelMaxime** [comment]
Yes I saw that, but as it's will be a small icon I took it for now. I prefer SVG format it's easier for a programmers to deal with it :)

If you know a way to have it not pixelised and not difform I took it 100% :D

**Pull request merged**
