### PR TITLE
Use npm for extensions

### PR DESCRIPTION
**Pull request by evilz**
Not sure on change of  index.html
Please test first

### CODE REVIEW

**Comment by MangelMaxime** [comment]
Cool, wikki published the extension over npm.
I would prefer to use the modules by extensions like:

- https://www.npmjs.com/package/bulma-checkradio
- https://www.npmjs.com/package/bulma-calendar

The reason being, it's easier to track changes. And we can fix, one extensions without needing to update the others if there is several extensions change in the module *bulma-extensions*

What's your opinion ?

**Comment by evilz** [comment]
Since the full package is not so clean I'm OK.
In fact I did not saw the pacakge by extensions :p

I'll will change to this.

**Comment by evilz** [comment]
I just add this https://ci.appveyor.com/project/evilz/fable-elmish-bulma 

seem to have a issue on webpack config.
In watchdocs the bundle.js is in  /bundle.js
In builddocs the bundle.js is in  /dist/js/bundle.js

**Comment by MangelMaxime** [comment]
Ok thanks.

I already need to change the webpack config so it will inject by itself into the html the required tags.

**Comment by evilz** [comment]
@alfonsogarciacaro How to build in production using your webpack ?
I can see this :
```
var isProduction = process.argv.indexOf("-p") >= 0;
console.log("Bundling for " + (isProduction ? "production" : "development") + "...");
```

But from calling `build.cmd` how to give the `-p` argument ? 
Thank

**Comment by MangelMaxime** [comment]
To build in production mode you will need to use "BuildDocs" target.

I just need to fix it.
This line: https://github.com/MangelMaxime/Fable.Elmish.Bulma/blob/feature/conversion/build.fsx#L99

Should become: `runDotnet "docs" "fable webpack --port free" -- -p`

**Comment by evilz** [comment]
I rebase, and change to individual npm.

I also change build.fx, webpack and index.html so it's working in dev and prod

**Comment by MangelMaxime** [comment]
Thanks for the PR, I will made some little modification in it before merging. And should be ok after.

**Comment by kunjee17** [comment]
Wow... new goodies are coming? I am excited. 👍

**Pull request merged**
